module Permute

export permute

function permute(a,b)
    result = [
        (a,b),
        (b,a),
     ]
     return result
end

function permute(a,b,c)
    result = [
        (a,b,c),
        (a,c,b),
        (b,a,c),
        (b,c,a),
        (c,a,b),
        (c,b,a),
     ]
     return result
end

function permute(a,b,c,d)
    result = [
        (a,b,c,d),
        (a,b,d,c),
        (a,c,b,d),
        (a,c,d,b),
        (a,d,b,c),
        (a,d,c,b),
        (b,a,c,d),
        (b,a,d,c),
        (b,c,a,d),
        (b,c,d,a),
        (b,d,a,c),
        (b,d,c,a),
        (c,a,b,d),
        (c,a,d,b),
        (c,b,a,d),
        (c,b,d,a),
        (c,d,a,b),
        (c,d,b,a),
        (d,a,b,c),
        (d,a,c,b),
        (d,b,a,c),
        (d,b,c,a),
        (d,c,a,b),
        (d,c,b,a),
     ]
     return result
end

function permute(a,b,c,d,e)
    result = [
        (a,b,c,d,e),
        (a,b,c,e,d),
        (a,b,d,c,e),
        (a,b,d,e,c),
        (a,b,e,c,d),
        (a,b,e,d,c),
        (a,c,b,d,e),
        (a,c,b,e,d),
        (a,c,d,b,e),
        (a,c,d,e,b),
        (a,c,e,b,d),
        (a,c,e,d,b),
        (a,d,b,c,e),
        (a,d,b,e,c),
        (a,d,c,b,e),
        (a,d,c,e,b),
        (a,d,e,b,c),
        (a,d,e,c,b),
        (a,e,b,c,d),
        (a,e,b,d,c),
        (a,e,c,b,d),
        (a,e,c,d,b),
        (a,e,d,b,c),
        (a,e,d,c,b),
        (b,a,c,d,e),
        (b,a,c,e,d),
        (b,a,d,c,e),
        (b,a,d,e,c),
        (b,a,e,c,d),
        (b,a,e,d,c),
        (b,c,a,d,e),
        (b,c,a,e,d),
        (b,c,d,a,e),
        (b,c,d,e,a),
        (b,c,e,a,d),
        (b,c,e,d,a),
        (b,d,a,c,e),
        (b,d,a,e,c),
        (b,d,c,a,e),
        (b,d,c,e,a),
        (b,d,e,a,c),
        (b,d,e,c,a),
        (b,e,a,c,d),
        (b,e,a,d,c),
        (b,e,c,a,d),
        (b,e,c,d,a),
        (b,e,d,a,c),
        (b,e,d,c,a),
        (c,a,b,d,e),
        (c,a,b,e,d),
        (c,a,d,b,e),
        (c,a,d,e,b),
        (c,a,e,b,d),
        (c,a,e,d,b),
        (c,b,a,d,e),
        (c,b,a,e,d),
        (c,b,d,a,e),
        (c,b,d,e,a),
        (c,b,e,a,d),
        (c,b,e,d,a),
        (c,d,a,b,e),
        (c,d,a,e,b),
        (c,d,b,a,e),
        (c,d,b,e,a),
        (c,d,e,a,b),
        (c,d,e,b,a),
        (c,e,a,b,d),
        (c,e,a,d,b),
        (c,e,b,a,d),
        (c,e,b,d,a),
        (c,e,d,a,b),
        (c,e,d,b,a),
        (d,a,b,c,e),
        (d,a,b,e,c),
        (d,a,c,b,e),
        (d,a,c,e,b),
        (d,a,e,b,c),
        (d,a,e,c,b),
        (d,b,a,c,e),
        (d,b,a,e,c),
        (d,b,c,a,e),
        (d,b,c,e,a),
        (d,b,e,a,c),
        (d,b,e,c,a),
        (d,c,a,b,e),
        (d,c,a,e,b),
        (d,c,b,a,e),
        (d,c,b,e,a),
        (d,c,e,a,b),
        (d,c,e,b,a),
        (d,e,a,b,c),
        (d,e,a,c,b),
        (d,e,b,a,c),
        (d,e,b,c,a),
        (d,e,c,a,b),
        (d,e,c,b,a),
        (e,a,b,c,d),
        (e,a,b,d,c),
        (e,a,c,b,d),
        (e,a,c,d,b),
        (e,a,d,b,c),
        (e,a,d,c,b),
        (e,b,a,c,d),
        (e,b,a,d,c),
        (e,b,c,a,d),
        (e,b,c,d,a),
        (e,b,d,a,c),
        (e,b,d,c,a),
        (e,c,a,b,d),
        (e,c,a,d,b),
        (e,c,b,a,d),
        (e,c,b,d,a),
        (e,c,d,a,b),
        (e,c,d,b,a),
        (e,d,a,b,c),
        (e,d,a,c,b),
        (e,d,b,a,c),
        (e,d,b,c,a),
        (e,d,c,a,b),
        (e,d,c,b,a),
    ]
    return result
end

end  # Permute
